CREATE TABLE Category(
	id INT PRIMARY KEY AUTO_INCREMENT,
	categoryName VARCHAR(50) UNIQUE NOT NULL,
	summary VARCHAR(255) NOT NULL,
	CreateTime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	State INT DEFAULT 1 NOT NULL,
	DelState INT DEFAULT 1 NOT NULL
);


CREATE TABLE Product(
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100) NOT NULL,
	brand VARCHAR(50) NOT NULL,
	summary VARCHAR(255) NULL,
	feng VARCHAR(50) NOT NULL,
	detail TEXT NOT NULL,
	CatoryId INT REFERENCES Category(Id),
	CreateTime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	State INT DEFAULT 1 NOT NULL,
	DelState INT DEFAULT 1 NOT NULL,
	CONSTRAINT FOREIGN KEY (CatoryId) REFERENCES Category (Id) 
	
);


CREATE TABLE ProductRule(
	Id INT PRIMARY KEY AUTO_INCREMENT,
	productId INT REFERENCES Product(Id),
	COUNT INT NOT NULL,
	color VARCHAR(50) NOT NULL,
	size VARCHAR(50) NOT NULL,
	YuanPrice DECIMAL NOT NULL,
	price DECIMAL NOT NULL,
	img1 VARCHAR(50) NULL,
	img2 VARCHAR(50) NULL,
	img3 VARCHAR(50) NULL,
	img4 VARCHAR(50) NULL,
	isDefault INT DEFAULT 0,
	isNew INT DEFAULT 0,
	isSale INT DEFAULT 0,
	CreateTime TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
	State INT DEFAULT 1 NOT NULL,
	DelState INT DEFAULT 1 NOT NULL,
	CONSTRAINT FOREIGN KEY (productId) REFERENCES Product (Id)

);


SELECT prduct.*,productrule.Id AS rid FROM product JOIN productrule ON product.Id = productrule.productId WHERE isDefault=1 AND isNew=1

